name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      postgres:
        image: postgres:2.9.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: harmon758/postgresql-action@v1
    - name: run migrations
      run: python manage.py migrate
    - name: Run Tests
      env:
        SECRET_KEY: secret
        DATABASE_NAME: postgresdb
        DATABASE_USER: userdb
        DATABASE_PASSWORD: passworddb
        DATABASE_HOST: postgres
        DEBUG_MODE: False
        DATABASE_PORT: 5432
      run: |
        python manage.py test
